language: php
addons:
  sonarqube: true
  
php:
- 7.0
before_script:
- ls
script:
- sonar-scanner -Dsonar.projectKey=testing  -Dsonar.host.url=http://54.255.213.201:9000 -Dsonar.sources=.  -Dsonar.login=$SONAR_TOKEN
