language: php
addons:
  sonarqube: true
  sonarcloud:
    token:
      secure: vQJo23DaX6ti0Tca3n3sfDR+cyOiVfSCvZmesBkM5j1hNxAJaayaAIESlr8TpP4KH6Q/QD/I7Ai+6QMLaN8902dM56CSfYsk08l/Bb6prprXLlWf04nzBLYLEYcYRjxS6A7kDifa+iDtDFnlY0RJv+6Hk2esRlMmK0mXm4KcQKgiVNGcmPMCK1kaReslw6Xj2wLj+gv8P/2w1xqWR1XE3EPuH2uK19xYDXwH6z5kQu7+ABm1qjaC3rE+WjtYk6JwmqjbXHI+ZWPBiQ3CZ6IKEmnATVN6ukD1Gb9M7agdxiwePpJzj+2TKlOmdDczjuhAiv5d2EyRkYISHfYLY0yYHD/oNgyWG+4r3i+40tX1KjDP20g2w6D1UVYg7JFzlMvq6ZVZ0IjET1hwNgn03Iq7vtCJBg4N4fqh+vEJNVvRqkNwfSjvEaCyvgdy9aHmEXBE2mQHtC/2px2/w4EeUCn4C2Jb5gY37CMCRuxA8zlfV2HulL5IoWyDt97D2jIH+WQuVxfj0BjOw06dkdUi+03IBSMd7ljzCs3NX/h0Ck7MjI2A5TTq7gmO0fl2BhJRJYXuVkW0JLaB2lvxNRXTF21cR/DE9lyosF8txxTCJjungxYQnF/pO2PWwBfM8iOBOd64MfmeUX/HyvIRUHew3XY3DWCLTJrAlYy4DqZlrjbby/c=
php:
- 7.0
before_script:
- ls
script:
- sonar-scanner -Dsonar.projectKey=testing  -Dsonar.host.url=http://sonarqube.bhinnekalocal.com:9000
  -Dsonar.sources=.  -Dsonar.login=dcbcb1014f52a7be8561edacafe85e045eb6f65c
env:
  global:
    secure: XeTZeh4r9c7yNt1m1MEHSGLLv/IC+vsZHEfP1hoECm2wRkGB8K8Wisu89C0kcZpm8d41Zf1+U0+vRAZA7eabsbdGsHhZP8KlSlPuw5ApPFHOGGAp3gKODVxTqeSVzSuaahVx+dXpAuKlCQLOsQHzPCV+7cIlY6SSOa6CS8nyQZRF2+lnROzSICN+WWtxCOnJkkH8hT8ukOKul7MdIMCGkoACygzlsMznUrbISlUET/EfYprd4PdtOOfHfgbw9OlyALODlGWhjm1CNLV+2VHzASdudwaICHmAHWSmh+pW15KKWplSZ2sUTyoSptn/9ynzZk4zxl5KdJ/mB0QAIqI0LpZy3dGTPnKS37Hzftn5edUMn9mxbypgGO6NhM+roPEOJvJbEGjskcv+pFaJZkduJxWgpt8mnTWfIWtEbzFLjViR98byWcaEbXJMcRHV54owqUeCBdfJWYriroCP53JjP6Nqz0wrUpxegR6ZYFxA7dxUu2u5TllRagjwDfw8ZuYp4NPOjAeLEKE4VlW1t4N8/apODFuBsTgZiHC14ZPK6pi54BxtI5FyCVomvPo/yr+pM7Hb7rE5Oo4ofe3L/x54LNx3rg/Ldy44g+OwPH33TNl6wP+fsimUXASLOZLwrj3IUCeLj6W0gLzP99shGPaEHqPyek6V5o54jnHB48mbieQ=
