language: php
addons:
  sonarqube: true
 
php:
- 7.0
before_script:
- ls
script:
- sonar-scanner -Dsonar.projectKey=testing  -Dsonar.host.url=http://54.255.213.2019000 -Dsonar.sources=.  -Dsonar.login=dcbcb1014f52a7be8561edacafe85e045eb6f65c
